/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnchorNavigation: typeof import('./src/components/AnchorNavigation.vue')['default']
    BBreadcrumb: typeof import('bootstrap-vue-next')['BBreadcrumb']
    BBreadcrumbItem: typeof import('bootstrap-vue-next')['BBreadcrumbItem']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    CustomSyntax: typeof import('./src/components/CustomSyntax.vue')['default']
    Jarallax: typeof import('./src/components/Jarallax.vue')['default']
    LightGallery: typeof import('./src/components/LightGallery.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    Parallax: typeof import('./src/components/Parallax.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    Rellax: typeof import('./src/components/Rellax.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanillaTilt: typeof import('./src/components/VanillaTilt.vue')['default']
    VideoPopup: typeof import('./src/components/VideoPopup.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBScrollspy: typeof import('bootstrap-vue-next')['vBScrollspy']
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
